name: Request Build

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, '⚗️ Request Build')
    name: Build app (if requested)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repository
        uses: actions/checkout@v4
        with:
          path: app
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ vars.FLUTTER_CHANNEL }}
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up keystore
        run: |
          echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > app/android/app/key.jks

      - name: Prepare version name
        id: version_name
        run: echo "version_name=$(echo "${{github.ref_name}}" | tr / _)" >> $GITHUB_OUTPUT

      - name: Build APK
        working-directory: app
        run: flutter build apk --release

      - name: Build App Bundle
        working-directory: app
        run: flutter build appbundle --release

      - name: Rename APK & App Bundle
        working-directory: app
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Debby_${{ steps.version_name.outputs.version_name }}.apk
          mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/Debby_${{ steps.version_name.outputs.version_name }}.aab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Debby_${{ steps.version_name.outputs.version_name }}.apk
          path: app/build/app/outputs/flutter-apk/Debby_${{ steps.version_name.outputs.version_name }}.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: Debby_${{ steps.version_name.outputs.version_name }}.aab
          path: app/build/app/outputs/bundle/release/Debby_${{ steps.version_name.outputs.version_name }}.aab

      - name: Comment build results
        uses: RubberDuckCrew/artifact2pr@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-if-no-artifacts: true

      - name: Remove "⚗️ Request Build" Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X DELETE \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/%E2%9A%97%EF%B8%8F%20Request%20Build
